name: List Previous Runs
on:
  workflow_dispatch:  # 手动触发测试

jobs:
  list-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Query workflow runs via API
        run: |
          # 替换为你的工作流文件名（如 .github/workflows/main.yml）
          WORKFLOW_FILE="core.yml"
          
          # 调用 API 获取最近 3 次成功的运行记录
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$WORKFLOW_FILE/runs?status=success&per_page=3")
          
          # 解析并输出 run_id
          echo "Previous successful run IDs:"
          echo "$RESPONSE" | jq -r '.workflow_runs[].id'
