name: List Previous Runs
on:
  workflow_dispatch:  # 手动触发测试

jobs:
  list-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Query workflow runs via API
        run: |

          CORE_FILE="core.yml"
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$CORE_FILE/runs?status=success&per_page=3")
          echo "Core Previous successful run IDs:"
          core_run_id=$(echo "$RESPONSE" | jq -r '.workflow_runs[].id')
          echo "CORE_ID=$core_run_id" >> $GITHUB_ENV

          GUI_FILE="gui.yml"
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$GUI_FILE/runs?status=success&per_page=3")
          echo "GUI Previous successful run IDs:"
          gui_run_id=$(echo "$RESPONSE" | jq -r '.workflow_runs[].id')
          echo "GUI_ID=$gui_run_id" >> $GITHUB_ENV

          MOBILE_FILE="mobile.yml"
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$MOBILE_FILE/runs?status=success&per_page=3")
          echo "MOBILE Previous successful run IDs:"
          mobile_run_id=$(echo "$RESPONSE" | jq -r '.workflow_runs[].id')
          echo "MOBILE_ID=$mobile_run_id" >> $GITHUB_ENV

      - name: print_id
        run: |
          echo "core" 
          echo env.CORE_ID
          echo "gui" 
          echo env.GUI_ID
          echo "mobile" 
          echo env.MOBILE_ID
          
